Get srch to comply with bash strict mode

diff --git a/srch b/srch
--- a/srch
+++ b/srch
@@ -1,4 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# https://github.com/olivergondza/bash-strict-mode
+set -euo pipefail
+trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
 
 ########
 
@@ -7,12 +10,15 @@ d="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 : ${SRCH_CONFIG="$SRCH_DIR/config"}
 : ${SRCH_ENGINES="$SRCH_DIR/engines"}
 
-. "$SRCH_DIR/lib/lib.sh"
+: ${SRCH_DEFAULT_ENGINE=""}
 
 if [ ! -d "$SRCH_DIR/engines" ]; then
     echo "Illegal SRCH_DIR provided: $SRCH_DIR" >&2
     exit 1
 fi
+
+. "$SRCH_DIR/lib/lib.sh"
+
 if [ ! -d "$SRCH_ENGINES" ]; then
     echo "Illegal SRCH_ENGINES provided: $SRCH_ENGINES" >&2
     exit 1
@@ -32,7 +38,7 @@ if [ ! -z "$SRCH_DEFAULT_ENGINE" -a ! -f "$SRCH_ENGINES/$SRCH_DEFAULT_ENGINE" ];
     exit 1
 fi
 
-if [ "$1" == '-h' -o "$1" == '--help' ]; then
+if [ "$#" -ge 1 ] && [ "$1" == '-h' -o "$1" == '--help' ]; then
     printf "Usage $0 <ENGINE_NAME> <SEARCH_STRING>\n\n"
 
     printf "SEARCH_STRING argument can be omitted to read it from STDIN. In case there is a default engine configured, it can be omitted too.\n\n"
@@ -47,23 +53,48 @@ if [ "$1" == '-h' -o "$1" == '--help' ]; then
     exit 0
 fi
 
-engine="$SRCH_DEFAULT_ENGINE"
-if [ -f "$SRCH_ENGINES/$1" -o -z "$SRCH_DEFAULT_ENGINE" ]; then
-    engine="$1"
-    shift
-fi
-engine_config="$SRCH_ENGINES/$engine"
-if [ ! -f "$engine_config" ]; then
-    if [ -z "$engine" ]; then
-        echo "No search engine specified"  >&2
+# Default y/n
+# 1st exist/or not
+#set -x
+
+if [ "$#" -ge 1 ]; then
+    if [ -f "$SRCH_ENGINES/$1" ]; then
+        engine="$1"
+        shift
+    elif [ ! -z "$SRCH_DEFAULT_ENGINE" ]; then
+        engine="$SRCH_DEFAULT_ENGINE"
     else
-        echo "No engine '$engine' configured"  >&2
+        echo >&2 "No engine '$1' configured"
+        _print_engines >&2
+        exit 1
     fi
-    _print_engines >&2
-    exit 1
+else
+    if [ ! -z "$SRCH_DEFAULT_ENGINE" ]; then
+        engine="$SRCH_DEFAULT_ENGINE"
+    else
+        echo >&2 "No search engine specified"
+        _print_engines >&2
+        exit 1
+    fi
 fi
 
-. $engine_config
+# engine="$SRCH_DEFAULT_ENGINE"
+# if [ "$#" -ge 1 ] && [ -f "$SRCH_ENGINES/$1" ]; then
+#     engine="$1"
+#     shift
+# fi
+# engine_config="$SRCH_ENGINES/$engine"
+# if [ ! -f "$engine_config" ]; then
+#     if [ -z "$engine" ]; then
+#         echo "No search engine specified"  >&2
+#     else
+#         echo "No engine '$engine' configured"  >&2
+#     fi
+#     _print_engines >&2
+#     exit 1
+# fi
+
+. "$SRCH_ENGINES/$engine"
 
 # urlencode all args
 if [ $# -eq 0 ]; then
@@ -91,7 +122,7 @@ if [ "$(type -t URL)" == "function" ]; then
   final_url="$(URL "${args[@]}")"
 else
   set -- "${args[@]}" # Set encoded values to positional args
-  final_url="$(eval "echo \"${URL}\"")"
+  final_url="$(set +u; eval "echo \"${URL}\"")"
 fi
 
 if [ ! -z "$BROWSER" ]; then
